#!/bin/sh

# Modify these two variables to yours
#export PATH=/opt/mipsel-linux-uclibc/bin:/opt/mipsel-linux-uclibc/usr/bin:"$PATH"
export SOURCE_PATH=/media/Data/dingoo/dingux/dev/openwrt/trunk/build_dir/target-_-
export INSTALL_PATH=/opt/mipsel-linux-uclibc/usr

export PKG_CONFIG_PATH=${INSTALL_PATH}/lib/pkgconfig
export CC=mipsel-linux-gcc

BUILDDIR=`pwd`

echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@ building libiconv-1.11 ..."
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"

# dependencies: none

cd ${BUILDDIR}
cd libiconv-1.11
./configure --prefix=${INSTALL_PATH} --host=mipsel-linux --enable-relocatable

make
make install
