#!/bin/sh

# Modify these two variables to yours
#export PATH=/opt/mipsel-linux-uclibc/bin:/opt/mipsel-linux-uclibc/usr/bin:"$PATH"
# export SOURCE_PATH=/media/Data/dingoo/dingux/dev/openwrt/trunk/build_dir/target-_-
export INSTALL_PATH=/opt/mipsel-linux-uclibc/usr

export PKG_CONFIG_PATH=${INSTALL_PATH}/lib/pkgconfig
#export CC=mipsel-linux-gcc

BUILDDIR=`pwd`

echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@ building pixman-0.16.2 ..."
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"

# dependencies: none

cd ${BUILDDIR}
cd pixman-0.16.2
./configure --prefix=${INSTALL_PATH} --host=mipsel-linux --target=mipsel-linux
make
make install
