#!/bin/sh

export INSTALL_PATH=/opt/mipsel-linux-uclibc/usr
export PKG_CONFIG_PATH=${INSTALL_PATH}/lib/pkgconfig
export DFB_DINGUX_PATH=/boot/local/directfb

BUILDDIR=`pwd`

echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@ building libxml2-2.7.6 ..."
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"

# dependencies: none

cd ${BUILDDIR}
cd libxml2-2.7.6
./configure --prefix=${INSTALL_PATH} --host=mipsel-linux
make
make install

echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@ building freetype-2.3.9 ..."
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"

# dependencies: none

cd ${BUILDDIR}
cd freetype-2.3.9
./configure --prefix=${INSTALL_PATH} --host=mipsel-linux --target=mipsel-linux

make
make install

echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@ building pixman-0.16.2 ..."
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"

# dependencies: none

cd ${BUILDDIR}
cd pixman-0.16.2
./configure --prefix=${INSTALL_PATH} --host=mipsel-linux --target=mipsel-linux
make
make install


echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@ building fontconfig-2.6.0 ..."
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"

# dependencies freetype, libxml2
cd ${BUILDDIR}

cd fontconfig-2.6.0
./configure --prefix=${INSTALL_PATH} --host=mipsel-linux --target=mipsel-linux --with-arch=mips

make
make install

echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@ building DirectFB-1.4.2 ..."
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"


mkdir ${DFB_DINGUX_PATH}
cd ${BUILDDIR}
cd DirectFB-1.4.2

# the first time executable files are put into the /boot/local/directfb folder
./configure --prefix=${INSTALL_PATH} --exec-prefix=${DFB_DINGUX_PATH} --host=mipsel-linux --disable-x11 --disable-osx --with-gfxdrivers=none --with-inputdrivers=keyboard,linuxinput CFLAGS="-I${INSTALL_PATH}/include" LDFLAGS="-L${INSTALL_PATH}/lib"

./configure --prefix=${INSTALL_PATH} --host=mipsel-linux --disable-x11 --disable-osx --with-gfxdrivers=none --with-inputdrivers=keyboard,linuxinput CFLAGS="-I${INSTALL_PATH}/include" LDFLAGS="-L${INSTALL_PATH}/lib"

echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@ building gettext-0.16.1 ..."
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"

# dependencies: none

cd ${BUILDDIR}
cd gettext-0.16.1
./configure --prefix=${INSTALL_PATH} --host=mipsel-linux --target=mipsel-linux
make
make install

echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@ building glib-2.22.2 ..."
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"

# dependencies: none

cd ${BUILDDIR}
cd glib-2.22.2

cd ..
cp ./script/glib-config/configure ./glib-2.22.2
cp ./script/glib-config/config.h ./glib-2.22.2
cp ./script/glib-config/config.cache ./glib-2.22.2
cd glib-2.22.2

./configure --prefix=${INSTALL_PATH} --host=mipsel-linux --target=mipsel-linux --cache-file=config.cache 

cd ..
cp ./script/glib-config/config.h ./glib-2.22.2
cd glib-2.22.2

make
make install

echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@ building atk-1.22.0 ..."
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"

# dependencies: glib

cd ${BUILDDIR}
cd atk-1.22.0
./configure --prefix=${INSTALL_PATH} --host=mipsel-linux
make
make install

echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@ building cairo-1.8.8 ..."
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"

# dependencies: libpng

cd ${BUILDDIR}
cd cairo-1.8.8
./configure --prefix=${INSTALL_PATH} --host=mipsel-linux --disable-xlib --disable-xlib-xrender --enable-directfb --enable-freetype --without-x --enable-glitz=no
make
make install

echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@ building pango-1.16.4 ..."
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"

# dependencies: glib, freetype, xml, cairo

cd ${BUILDDIR}
tar xjf ./pango-1.16.4.tar.bz2
cd pango-1.16.4

sed -i -e 's/have_cairo=false/have_cairo=true/g' configure
sed -i -e 's/have_cairo_png=false/have_cairo_png=true/g' configure
sed -i -e 's/have_cairo_freetype=false/have_cairo_freetype=true/g' configure

./configure --prefix=${INSTALL_PATH} --host=mipsel-linux --without-x LDFLAGS="-L${INSTALL_PATH}/lib -lxml2"
make
make install

echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@ building gtk+-2.10.14 ..."
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"

# dependencies: GLib, Pango, ATK, cairo, DirectFB

cd ${BUILDDIR}
tar xjf ./gtk+-2.10.14.tar.bz2
cd gtk+-2.10.14
./configure --prefix=${INSTALL_PATH} --host=mipsel-linux --with-gdktarget=directfb --without-x 

## set config.h
echo '#define __u32 u32'>> config.h
echo '#define __u8 u8'>> config.h

## 
cd "${BUILDDIR}/gtk+-2.10.14/gdk/directfb"
for file in gdkdrawable-directfb gdkimage-directfb gdkinput-directfb gdkpixmap-directfb gdkwindow-directfb; do

        C="$file.c"
        TMP="$file.tmp"
        BAK="$file.bak"

        sed 's/G_GNUC_FUNCTION/G_STRLOC/g' $C>$TMP

        mv $C $BAK
        mv $TMP $C
        #echo $file
done

## remove demos folder from Makefile
cd ${BUILDDIR}/gtk+-2.10.14
file=Makefile
SRC="$file"
TMP="$file.tmp"
BAK="$file.bak"
sed 's/SRC_SUBDIRS = gdk-pixbuf gdk gtk modules demos tests perf contrib/SRC_SUBDIRS = gdk-pixbuf gdk gtk modules tests perf contrib/'  $SRC>$TMP

mv $SRC $BAK
mv $TMP $SRC

## build
cd ${BUILDDIR}/gtk+-2.10.14

make
make install

echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"
echo "@@               FINISHED                  @@"
echo "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@"


